let oyunKurucular=["Malcolm Brogdon","Derrick White","Marcus Smart","Payton Pritchard","JD Davison","Jrue Holiday","Jevon Carter","James Harden","Tyrese Maxey","De'Anthony Melton","Mac McClung","Shake Milton","Donovan Mitchell","Darius Garland","Ricky Rubio","Rualzinho Neto","Ben Simmons","Seth Curry","Edmond Sumner","Patty Mills","Spencer Dinwiddie","Jalen Brunson","Derrick Rose","Immanuel Quickley","Miles McBride","DaQuan Jeffries","Tyler Herro","Kyle Lowry","Gabe Vincent","Trae Young","Dejounte Murray","Aaron Holiday","Vît Krejci","Monté Morris","Delon Wright","Jordan Doodwin","Kendrick Nunn","Fred VanVleet","Gary Trent Jr.","Dalano Banton","Malachi Flynn","Jeff Dowtin","Lonzo Ball","Ayo Dosunmu","Goran Dragic","Alex Caruso","Coby White","Carlik Jones","Tyrese Haliburton","Andrew Nembhard","T.J. MacConnell","Trevelin Queen","George Hill","Markelle Fultz","Jalen Suggs","Cole Anthony","R.J. Hampton","LaMelo Ball","Terry Rozier","Dennis Smith Jr.","James Bouknight","Théo Maledon","Jaden Ivey","Cade Cunningham","Killian Hayes","Cory Joseph","Jamal Murray","Collin Gillespie","Ish Smith","Reggie Jackson","Ja Morant","Tyus Jones","Kennedy Chandler","De'Aaron Fox","Davion Mitchell","Matthew Dellavedova","Jason Preston","Nah'Shon Hyland","Chris Paul","Cameron Payne","Saben Lee","Luka Doncic","Jaden Hardy","Kyrie Ivring","Frank Ntilikina","McKinley Wright IV","Jose Alvarado","C.J. McCollum","Kira Lewis Jr.","Jaylen Nowell","Mike Conley Jr.","Jordan McLaughlin","Stephen Curry","Jordan Poole","Donte DiVincenzo","Ty Jerome","Gary Payton II","Shai Gilgeous-Alexander","Josh Giddey","Tre Mann","Isaiah Joe","Jordan Clarkson","Collin Sexton","Russell Westbrook","Damian Lillard","Anfernee Simons","Ryan Arcidiacono","Dennis Schröder","Scotty Pippen Jr.","D'Angelo Russell","Tre Jones","Devonte Graham","Kevin Porter Jr.","TyTy Washington","Trevor Hudgins"];
let oyunKurucuNumaraları=["13","9","36","11","20","21","5","1","0","8","9","18","45","10","13","19","10","30","4","8","26","11","4","5","2","8","14","7","2","11","5","3","27","22","55","7","20","23","33","45","22","20","2","12","7","6","0","22","0","2","9","8","7","20","4","50","13","1","3","8","9","23","2","7","18","27","21","14","91","12","21","1","5","15","8","0","3","3","15","38","77","3","2","21","23","15","3","13","4","10","6","30","3","0","10","8","2","3","23","11","00","2","71","0","1","51","17","14","0","33","4","3","0","12"];
let oyunKurucuTakimlar=["Boston Celtics","Boston Celtics","Boston Celtics","Boston Celtics","Boston Celtics","Milwaukee Bucks","Milwaukee Bucks","Philadelphia 76ers","Philadelphia 76ers","Philadelphia 76ers","Philadelphia 76ers","Philadelphia 76ers","Cleveland Cavaliers","Cleveland Cavaliers","Cleveland Cavaliers","Cleveland Cavaliers","Brooklyn Nets","Brooklyn Nets","Brooklyn Nets","Brooklyn Nets","Brooklyn Nets","New York Knicks","New York Knicks","New York Knicks","New York Knicks","New York Knicks","Miami Heat","Miami Heat","Miami Heat","Atlanta Hawks","Atlanta Hawks","Atlanta Hawks","Atlanta Hawks","Washington Wizards","Washington Wizards","Washington Wizards","Washington Wizards","Toronto Raptors","Toronto Raptors","Toronto Raptors","Toronto Raptors","Toronto Raptors","Chicago Bulls","Chicago Bulls","Chicago Bulls","Chicago Bulls","Chicago Bulls","Chicago Bulls","Indiana Pacers","Indiana Pacers","Indiana Pacers","Indiana Pacers","Indiana Pacers","Orlando Magic","Orlando Magic","Orlando Magic","Orlando Magic","Charlotte Hornets","Charlotte Hornets","Charlotte Hornets","Charlotte Hornets","Charlotte Hornets","Detroit Pistons","Detroit Pistons","Detroit Pistons","Detroit Pistons","Denver Nuggets","Denver Nuggets","Denver Nuggets","Denver Nuggets","Memphis Grizzlies","Memphis Grizzlies","Memphis Grizzlies","Sacramento Kings","Sacramento Kings","Sacramento Kings","Los Angeles Clippers","Los Angeles Clippers","Phoenix Suns","Phoenix Suns","Phoenix Suns","Dallas Mavericks","Dallas Mavericks","Dallas Mavericks","Dallas Mavericks","Dallas Mavericks","New Orleans Pelicans","New Orleans Pelicans","New Orleans Pelicans","Minnesota Timberwolves","Minnesota Timberwolves","Minnesota Timberwolves","Golden State Warriors","Golden State Warriors","Golden State Warriors","Golden State Warriors","Golden State Warriors","Oklahoma City Thunder","Oklahoma City Thunder","Oklahoma City Thunder","Oklahoma City Thunder","Utah Jazz","Utah Jazz","Utah Jazz","Portland Trail Blazers","Portland Trail Blazers","Portland Trail Blazers","Los Angeles Lakers","Los Angeles Lakers","Los Angeles Lakers","San Antonio Spurs","San Antonio Spurs","Houston Rockets","Houston Rockets","Houston Rockets"];

let shootingGuardlar=["Malcolm Brogdon","Derrick White","Marcus Smart","Payton Pritchard","JD Davison","Jrue Holiday","Jevon Carter","James Harden","Tyrese Maxey","De'Anthony Melton","Mac McClung","Shake Milton","Donovan Mitchell","Darius Garland","Ricky Rubio","Rualzinho Neto",];
let shootingGuardNumaraları=["13","9","36","11","20","21","5","1","0","8","9","18","45","10","13","19",];

const button=document.getElementById("btnDegistir");
const oyunKurucu=document.getElementById("oyunKurucu");

const oyunKurucuNumara=document.getElementById("oyunKurucuNumara");

const oyunKurucuTakim=document.getElementById("oyunKurucuTakim");114

let sayi1=Math.floor(Math.random()*113);
oyunKurucu.innerHTML=oyunKurucular[sayi1];
oyunKurucuNumara.innerHTML=oyunKurucuNumaraları[sayi1];
oyunKurucuTakim.innerHTML=oyunKurucuTakimlar[sayi1];

button.addEventListener("click", ()=>{
    let sayi1=Math.floor(Math.random()*113);
    oyunKurucu.innerHTML=oyunKurucular[sayi1];
    oyunKurucuNumara.innerHTML=oyunKurucuNumaraları[sayi1];
    oyunKurucuTakim.innerHTML=oyunKurucuTakimlar[sayi1];
});
